apiVersion: v1
kind: ConfigMap

metadata:
  name: db-configmap

data:
  MYSQL_DATABASE: "biblioteca"
  MYSQL_USER: "user"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/biblioteca"
  SPRING_DATASOURCE_USERNAME: "user"

  my.cnf: |
    [mysqld]
    mysql_native_password=ON
